<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Linear Regression – Econometrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-hypothesis-tests.html" rel="next">
<link href="./03-statistics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-866c0150a82ceb70419aea9aa33b875d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-linear-regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Econometrics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to <code>R</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Probability for Economists</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review of Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-linear-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-nonlinear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Nonlinear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-potential-issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Panel Data Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Discrete Choice Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercises</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cruscotto-opere-pubbliche/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">In-Class Exercise: Public Works Cost Overruns Across Italian Provinces</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-are-x-and-y-related" id="toc-how-are-x-and-y-related" class="nav-link active" data-scroll-target="#how-are-x-and-y-related"><span class="header-section-number">5.1</span> How are <code>x</code> and <code>y</code> related?</a>
  <ul class="collapse">
  <li><a href="#data-on-cars" id="toc-data-on-cars" class="nav-link" data-scroll-target="#data-on-cars"><span class="header-section-number">5.1.1</span> Data on Cars</a></li>
  <li><a href="#how-are-speed-and-dist-related" id="toc-how-are-speed-and-dist-related" class="nav-link" data-scroll-target="#how-are-speed-and-dist-related"><span class="header-section-number">5.1.2</span> How are <code>speed</code> and <code>dist</code> related?</a></li>
  <li><a href="#choosing-the-best-line" id="toc-choosing-the-best-line" class="nav-link" data-scroll-target="#choosing-the-best-line"><span class="header-section-number">5.1.3</span> Choosing the Best Line</a></li>
  </ul></li>
  <li><a href="#OLS" id="toc-OLS" class="nav-link" data-scroll-target="#OLS"><span class="header-section-number">5.2</span> Ordinary Least Squares (OLS) Estimator</a>
  <ul class="collapse">
  <li><a href="#linear-regression-without-regressor" id="toc-linear-regression-without-regressor" class="nav-link" data-scroll-target="#linear-regression-without-regressor"><span class="header-section-number">5.2.1</span> Linear Regression without Regressor</a></li>
  <li><a href="#regression-without-an-intercept" id="toc-regression-without-an-intercept" class="nav-link" data-scroll-target="#regression-without-an-intercept"><span class="header-section-number">5.2.2</span> Regression without an Intercept</a></li>
  <li><a href="#centering-a-regression" id="toc-centering-a-regression" class="nav-link" data-scroll-target="#centering-a-regression"><span class="header-section-number">5.2.3</span> Centering A Regression</a></li>
  <li><a href="#reg-standard" id="toc-reg-standard" class="nav-link" data-scroll-target="#reg-standard"><span class="header-section-number">5.2.4</span> Standardizing A Regression</a></li>
  </ul></li>
  <li><a href="#pred-resids" id="toc-pred-resids" class="nav-link" data-scroll-target="#pred-resids"><span class="header-section-number">5.3</span> Predictions and Residuals</a></li>
  <li><a href="#correlation-covariance-and-linearity" id="toc-correlation-covariance-and-linearity" class="nav-link" data-scroll-target="#correlation-covariance-and-linearity"><span class="header-section-number">5.4</span> Correlation, Covariance and Linearity</a>
  <ul class="collapse">
  <li><a href="#non-linear-relationships-in-data" id="toc-non-linear-relationships-in-data" class="nav-link" data-scroll-target="#non-linear-relationships-in-data"><span class="header-section-number">5.4.1</span> Non-Linear Relationships in Data</a></li>
  </ul></li>
  <li><a href="#analysing-vary" id="toc-analysing-vary" class="nav-link" data-scroll-target="#analysing-vary"><span class="header-section-number">5.5</span> Analysing <span class="math inline">Var(y)</span></a></li>
  <li><a href="#assessing-the-goodness-of-fit" id="toc-assessing-the-goodness-of-fit" class="nav-link" data-scroll-target="#assessing-the-goodness-of-fit"><span class="header-section-number">5.6</span> Assessing the <em>Goodness of Fit</em></a></li>
  <li><a href="#an-example-a-log-wage-equation" id="toc-an-example-a-log-wage-equation" class="nav-link" data-scroll-target="#an-example-a-log-wage-equation"><span class="header-section-number">5.7</span> An Example: A Log Wage Equation</a></li>
  <li><a href="#scaling-regressions" id="toc-scaling-regressions" class="nav-link" data-scroll-target="#scaling-regressions"><span class="header-section-number">5.8</span> Scaling Regressions</a></li>
  <li><a href="#a-particular-rescaling-the-log-transform" id="toc-a-particular-rescaling-the-log-transform" class="nav-link" data-scroll-target="#a-particular-rescaling-the-log-transform"><span class="header-section-number">5.9</span> A Particular Rescaling: The <span class="math inline">\log</span> Transform</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="linreg" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter we will learn an additional way how one can represent the relationship between <em>outcome</em>, or <em>dependent</em> variable variable <span class="math inline">y</span> and an <em>explanatory</em> or <em>independent</em> variable <span class="math inline">x</span>. We will refer throughout to the graphical representation of a collection of independent observations on <span class="math inline">x</span> and <span class="math inline">y</span>, i.e., a <em>dataset</em>.</p>
<section id="how-are-x-and-y-related" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="how-are-x-and-y-related"><span class="header-section-number">5.1</span> How are <code>x</code> and <code>y</code> related?</h2>
<section id="data-on-cars" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="data-on-cars"><span class="header-section-number">5.1.1</span> Data on Cars</h3>
<p>We will look at the built-in <code>cars</code> dataset. Let’s get a view of this by just typing <code>View(cars)</code> in Rstudio. You can see something like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  speed dist
1     4    2
2     4   10
3     7    4
4     7   22
5     8   16
6     9   10</code></pre>
</div>
</div>
<p>We have a <code>data.frame</code> with two columns: <code>speed</code> and <code>dist</code>. Type <code>help(cars)</code> to find out more about the dataset. There you could read that</p>
<blockquote class="blockquote">
<p>The data give the speed of cars (mph) and the distances taken to stop (ft).</p>
</blockquote>
<p>It’s good practice to know the extent of a dataset. You could just type</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(cars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50  2</code></pre>
</div>
</div>
<p>to find out that we have 50 rows and 2 columns. A central question that we want to ask now is the following:</p>
</section>
<section id="how-are-speed-and-dist-related" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="how-are-speed-and-dist-related"><span class="header-section-number">5.1.2</span> How are <code>speed</code> and <code>dist</code> related?</h3>
<p>The simplest way to start is to plot the data. Remembering that we view each row of a data.frame as an observation, we could just label one axis of a graph <code>speed</code>, and the other one <code>dist</code>, and go through our table above row by row. We just have to read off the x/y coordinates and mark them in the graph. In <code>R</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> cars,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Speed (in Miles Per Hour)"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Stopping Distance (in Feet)"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Stopping Distance vs Speed"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch  =</span> <span class="dv">20</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex  =</span> <span class="dv">2</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here, each dot represents one observation. In this case, one particular measurement <code>speed</code> and <code>dist</code> for a car. Now, again:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>How are <code>speed</code> and <code>dist</code> related? How could one best <em>summarize</em> this relationship?</p>
</div>
</div>
<p><br> One thing we could do, is draw a straight line through this scatterplot, like so:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> cars,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Speed (in Miles Per Hour)"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Stopping Distance (in Feet)"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Stopping Distance vs Speed"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch  =</span> <span class="dv">20</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex  =</span> <span class="dv">2</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col  =</span> <span class="st">"red"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a =</span> <span class="dv">60</span>,<span class="at">b =</span> <span class="dv">0</span>,<span class="at">lw=</span><span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now that doesn’t seem a particularly <em>good</em> way to summarize the relationship. Clearly, a <em>better</em> line would be not be flat, but have a <em>slope</em>, i.e.&nbsp;go upwards:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>That is slightly better. However, the line seems at too high a level - the point at which it crosses the y-axis is called the <em>intercept</em>; and it’s too high. We just learned how to represent a <em>line</em>, i.e.&nbsp;with two numbers called <em>intercept</em> and <em>slope</em>. Let’s write down a simple formula which represents a line where some outcome <span class="math inline">z</span> is related to a variable <span class="math inline">x</span>:</p>
<p><span id="eq-bline"><span class="math display">
z = b_0 + b_1 x
\tag{5.1}</span></span></p>
<p>Here <span class="math inline">b_0</span> represents the value of the intercept (i.e.&nbsp;<span class="math inline">z</span> when <span class="math inline">x=0</span>), and <span class="math inline">b_1</span> is the value of the slope. The question for us is now: How to choose the number <span class="math inline">b_0</span> and <span class="math inline">b_1</span> such that the result is the <strong>good</strong> line?</p>
</section>
<section id="choosing-the-best-line" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="choosing-the-best-line"><span class="header-section-number">5.1.3</span> Choosing the Best Line</h3>
<p>In order to be able to reason about good or bad line, we need to denote the <em>output</em> of equation <a href="#eq-bline" class="quarto-xref">Equation&nbsp;<span>5.1</span></a>. We call the value <span class="math inline">\hat{y}_i</span> the <em>predicted value</em> for obseration <span class="math inline">i</span>, after having chosen some particular values <span class="math inline">b_0</span> and <span class="math inline">b_1</span>:</p>
<p><span id="eq-abline-pred"><span class="math display">
\hat{y}_i = b_0 + b_1 x_i
\tag{5.2}</span></span></p>
<p>In general it is likely that we won’t be able to choose <span class="math inline">b_0</span> and <span class="math inline">b_1</span> in such as way as to provide a perfect prediction, i.e.&nbsp;one where <span class="math inline">\hat{y}_i = y_i</span> for all <span class="math inline">i</span>. That is, we expect to make an <em>error</em> in our prediction <span class="math inline">\hat{y}_i</span>, so let’s denote this value <span class="math inline">e_i</span>. If we acknowlegdge that we will make errors, let’s at least make them as small as possible! Exactly this is going to be our task now.</p>
<p>Suppose we have the following set of 9 observations on <code>x</code> and <code>y</code>, and we put the <em>best</em> straight line into it, that we can think of. It would look like this:</p>
<div class="cell" data-align="center">
<div class="cell-output-display">
<div id="fig-line-arrows" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-line-arrows-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-linear-regression_files/figure-html/fig-line-arrows-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-line-arrows-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: The best line and its errors
</figcaption>
</figure>
</div>
</div>
</div>
<p>Here, the red arrows indicate the <strong>distance</strong> between the prediction (i.e.&nbsp;the black line) to each data point, in other words, each arrow is a particular <span class="math inline">e_i</span>. An upward pointing arrow indicates a positive value of a particular <span class="math inline">e_i</span>, and vice versa for downward pointing arrows. The erros are also called <em>residuals</em>, which comes from the way can write the equation for this relationship between two particular values <span class="math inline">(y_i,x_i)</span> belonging to observation <span class="math inline">i</span>:</p>
<p><span id="eq-abline"><span class="math display">
y_i = b_0 + b_1 x_i + e_i
\tag{5.3}</span></span></p>
<p>You realize of course that <span class="math inline">\hat{y}_i = y_i - e_i</span>, which just means that our prediction is the observed value <span class="math inline">y_i</span> minus any error <span class="math inline">e_i</span> we make. In other words, <span class="math inline">e_i</span> is what is left to be explained on top of the line <span class="math inline">b_0 + b_1 x_i</span>, hence, it’s a residual to explain <span class="math inline">y_i</span>. Here are <span class="math inline">y,\hat{y}</span> and the resulting <span class="math inline">e</span> which are plotted in figure <a href="#fig-line-arrows" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">x</th>
<th style="text-align: center;">y</th>
<th style="text-align: center;">y_hat</th>
<th style="text-align: center;">error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">2.09</td>
<td style="text-align: center;">2.57</td>
<td style="text-align: center;">-0.48</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.25</td>
<td style="text-align: center;">2.79</td>
<td style="text-align: center;">3.41</td>
<td style="text-align: center;">-0.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2.50</td>
<td style="text-align: center;">6.49</td>
<td style="text-align: center;">4.25</td>
<td style="text-align: center;">2.24</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.75</td>
<td style="text-align: center;">1.71</td>
<td style="text-align: center;">5.10</td>
<td style="text-align: center;">-3.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5.00</td>
<td style="text-align: center;">9.89</td>
<td style="text-align: center;">5.94</td>
<td style="text-align: center;">3.95</td>
</tr>
<tr class="even">
<td style="text-align: center;">6.25</td>
<td style="text-align: center;">7.62</td>
<td style="text-align: center;">6.78</td>
<td style="text-align: center;">0.83</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7.50</td>
<td style="text-align: center;">4.86</td>
<td style="text-align: center;">7.63</td>
<td style="text-align: center;">-2.77</td>
</tr>
<tr class="even">
<td style="text-align: center;">8.75</td>
<td style="text-align: center;">7.38</td>
<td style="text-align: center;">8.47</td>
<td style="text-align: center;">-1.09</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10.00</td>
<td style="text-align: center;">10.63</td>
<td style="text-align: center;">9.31</td>
<td style="text-align: center;">1.32</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If our line was a <strong>perfect fit</strong> to the data, all <span class="math inline">e_i = 0</span>, and the column <code>error</code> would display <code>0</code> for each row - there would be no errors at all. (All points in figure <a href="#fig-line-arrows" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> would perfectly line up on a straight line).</p>
<p>Now, back to our claim that this particular line is the <em>best</em> line. What exactly characterizes this best line? We now come back to what we said above - <em>how to make the errors as small as possible</em>? Keeping in mind that each residual <span class="math inline">e_i</span> is <span class="math inline">y_i - \hat{y}_i</span>, we have the following minization problem to solve:</p>
<p><span id="eq-ols-min"><span class="math display">
\begin{align}
e_i &amp; = y_i - \hat{y}_i = y_i - \underbrace{\left(b_0 + b_1 x_i\right)}_\text{prediction}\\
e_1^2 + \dots + e_N^2 &amp;= \sum_{i=1}^N e_i^2 \equiv \text{SSR}(b_0,b_1) \\
(b_0,b_1) &amp;= \arg \min_{\text{int},\text{slope}} \sum_{i=1}^N \left[y_i - \left(\text{int} + \text{slope } x_i\right)\right]^2
\end{align}
\tag{5.4}</span></span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The best line chooses <span class="math inline">b_0</span> and <span class="math inline">b_1</span> so as to minimize the sum of <strong>squared residuals</strong> (SSR).</p>
</div>
</div>
<p><br></p>
<p>Wait a moment, why <em>squared</em> residuals? This is easy to understand: suppose that instead, we wanted to just make the <em>sum</em> of the arrows in figure <a href="#fig-line-arrows" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> as small as possible (that is, no squares). Choosing our line to make this number small would not give a particularly good representation of the data – given that errors of opposite sign and equal magnitude offset, we could have very long arrows (but of opposite signs), and a poor resulting line. Squaring each error avoids this (because now negative errors get positive values!)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-line-squares" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-line-squares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04-linear-regression_files/figure-html/fig-line-squares-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-line-squares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: The best line and its SQUARED errors.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We illustrate this in figure <a href="#fig-line-squares" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>. This is the same data as in figure <a href="#fig-line-arrows" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, but instead of arrows of length <span class="math inline">e_i</span> for each observation <span class="math inline">i</span>, now we draw a square with side <span class="math inline">e_i</span>, i.e.&nbsp;an area of <span class="math inline">e_i^2</span>. We have two apps for you at this point, one where you have to try and find the best line by choosing <span class="math inline">b_0</span> and <span class="math inline">b_1</span>, only focusing on the sum of errors (and not their square), and a second one focusing on squared errors:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ScPoApps)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"reg_simple_arrows"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"reg_simple"</span>) <span class="co"># with squared errors</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"SSR_cone"</span>) <span class="co"># visualize the minimzation problem from above!</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Most of our <code>apps</code> have an associated <code>about</code> document, which gives extra information and explanations. After you have looked at all three apps, we invite you thus to have a look at the associated explainers by typing</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aboutApp</span>(<span class="st">"reg_simple_arrows"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aboutApp</span>(<span class="st">"reg_simple"</span>) </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">aboutApp</span>(<span class="st">"SSR_cone"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="OLS" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="OLS"><span class="header-section-number">5.2</span> Ordinary Least Squares (OLS) Estimator</h2>
<p>The method to compute (or <em>estimate</em>) <span class="math inline">b_0</span> and <span class="math inline">b_1</span> we illustrated above is called <em>Ordinary Least Squares</em>, or OLS. <span class="math inline">b_0</span> and <span class="math inline">b_1</span> are therefore also often called the <em>OLS coefficients</em>. By solving problem <a href="#eq-ols-min" class="quarto-xref">Equation&nbsp;<span>5.4</span></a> one can derive an explicit formula for them:</p>
<p><span id="eq-beta1hat"><span class="math display">
b_1 = \frac{cov(x,y)}{var(x)},  
\tag{5.5}</span></span></p>
<p>i.e.&nbsp;the estimate of the slope coefficient is the covariance between <span class="math inline">x</span> and <span class="math inline">y</span> divided by the variance of <span class="math inline">x</span>, both computed from our sample of data. With <span class="math inline">b_1</span> in hand, we can get the estimate for the intercept as</p>
<p><span id="eq-beta0hat"><span class="math display">
b_0 = \bar{y} - b_1 \bar{x}.
\tag{5.6}</span></span></p>
<p>where <span class="math inline">\bar{z}</span> denotes the sample mean of variable <span class="math inline">z</span>. The interpretation of the OLS slope coefficient <span class="math inline">b_1</span> is as follows. Given a line as in <span class="math inline">y = b_0 + b_1 x</span>,</p>
<ul>
<li><span class="math inline">b_1 = \frac{d y}{d x}</span> measures the change in <span class="math inline">y</span> resulting from a one unit change in <span class="math inline">x</span></li>
<li>For example, if <span class="math inline">y</span> is wage and <span class="math inline">x</span> is years of education, <span class="math inline">b_1</span> would measure the effect of an additional year of education on wages.</li>
</ul>
<p>There is an alternative representation for the OLS slope coefficient which relates to the <em>correlation coefficient</em> <span class="math inline">r</span>. Remember from section @ref(summarize-two) that <span class="math inline">r = \frac{cov(x,y)}{s_x s_y}</span>, where <span class="math inline">s_z</span> is the standard deviation of variable <span class="math inline">z</span>. With this in hand, we can derive the OLS slope coefficient as</p>
<p><span id="eq-beta1-r"><span class="math display">
\begin{align}
b_1 &amp;= \frac{cov(x,y)}{var(x)}\\
    &amp;= \frac{cov(x,y)}{s_x s_x} \\
    &amp;= r\frac{s_y}{s_x}
\end{align}
\tag{5.7}</span></span></p>
<p>In other words, the slope coefficient is equal to the correlation coefficient <span class="math inline">r</span> times the ratio of standard deviations of <span class="math inline">y</span> and <span class="math inline">x</span>.</p>
<section id="linear-regression-without-regressor" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="linear-regression-without-regressor"><span class="header-section-number">5.2.1</span> Linear Regression without Regressor</h3>
<p>There are several important special cases for the linear regression introduced above. Let’s start with the most obvious one: What is the meaning of running a regression <em>without any regressor</em>, i.e.&nbsp;without a <span class="math inline">x</span>? Our line becomes very simple. Instead of <a href="#eq-bline" class="quarto-xref">Equation&nbsp;<span>5.1</span></a>, we get</p>
<p><span id="eq-b0line"><span class="math display">
y = b_0.
\tag{5.8}</span></span></p>
<p>This means that our minization problem in <a href="#eq-ols-min" class="quarto-xref">Equation&nbsp;<span>5.4</span></a> <em>also</em> becomes very simple: We only have to choose <span class="math inline">b_0</span>! We have</p>
<p><span class="math display">
b_0 = \arg\min_{\text{int}} \sum_{i=1}^N \left[y_i - \text{int}\right]^2,
</span> which is a quadratic equation with a unique optimum such that <span class="math display">
b_0 = \frac{1}{N} \sum_{i=1}^N y_i = \overline{y}.
</span></p>
<div class="cell" type="tip">
<div class="tip">
<p>
Least Squares <strong>without regressor</strong> <span class="math inline">(x)</span> estimates the sample mean of the outcome variable <span class="math inline">(y)</span>, i.e.&nbsp;it produces <span class="math inline">()</span>.
</p>
</div>
</div>
</section>
<section id="regression-without-an-intercept" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="regression-without-an-intercept"><span class="header-section-number">5.2.2</span> Regression without an Intercept</h3>
<p>We follow the same logic here, just that we miss another bit from our initial equation and the minimisation problem in <a href="#eq-ols-min" class="quarto-xref">Equation&nbsp;<span>5.4</span></a> now becomes:</p>
<p><span id="eq-b1line"><span class="math display">
\begin{align}
b_1 &amp;= \arg\min_{\text{slope}} \sum_{i=1}^N \left[y_i - \text{slope } x_i \right]^2\\
\mapsto b_1 &amp;= \frac{\frac{1}{N}\sum_{i=1}^N x_i y_i}{\frac{1}{N}\sum_{i=1}^N x_i^2} = \frac{\bar{x} \bar{y}}{\overline{x^2}}
\end{align}
\tag{5.9}</span></span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Least Squares <strong>without intercept</strong> (i.e.&nbsp;with <span class="math inline">b_0=0</span>) is a line that passes through the origin.</p>
</div>
</div>
<p><br></p>
<p>In this case we only get to choose the slope <span class="math inline">b_1</span> of this anchored line.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> You should now try out both of those restrictions on our linear model by spending some time with</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"reg_constrained"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="centering-a-regression" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="centering-a-regression"><span class="header-section-number">5.2.3</span> Centering A Regression</h3>
<p>By <em>centering</em> or <em>demeaning</em> a regression, we mean to substract from both <span class="math inline">y</span> and <span class="math inline">x</span> their respective averages to obtain <span class="math inline">\tilde{y}_i = y_i - \bar{y}</span> and <span class="math inline">\tilde{x}_i = x_i - \bar{x}</span>. We then run a regression <em>without intercept</em> as above. That is, we use <span class="math inline">\tilde{x}_i,\tilde{y}_i</span> instead of <span class="math inline">x_i,y_i</span> in @ref(eq:b1line) to obtain our slope estimate <span class="math inline">b_1</span>:</p>
<p>$$ b_1 &amp;= \ &amp;= \ &amp;= </p>
<p>\end{align} $$ {#eq-bline-centered}</p>
<p>This last expression is <em>identical</em> to the one in <span class="citation" data-cites="eq1beta1hat">(<a href="references.html#ref-eq1beta1hat" role="doc-biblioref"><strong>eq1beta1hat?</strong></a>)</span>! It’s the standard OLS estimate for the slope coefficient. We note the following:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Adding a constant to a regression produces the same result as centering all variables and estimating without intercept. So, unless all variables are centered, <strong>always</strong> include an intercept in the regression.</p>
</div>
</div>
<p><br> To get a better feel for what is going on here, you can try this out now by yourself by typing:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"demeaned_reg"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="reg-standard" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="reg-standard"><span class="header-section-number">5.2.4</span> Standardizing A Regression</h3>
<p><em>Standardizing</em> a variable <span class="math inline">z</span> means to demean as above, but in addition to divide the demeaned value by its own standard deviation. Similarly to what we did above for <em>centering</em>, we define transformed variables <span class="math inline">\breve{y}_i = \frac{y_i-\bar{y}}{\sigma_y}</span> and <span class="math inline">\breve{x}_i = \frac{x_i-\bar{x}}{\sigma_x}</span> where <span class="math inline">\sigma_z</span> is the standard deviation of variable <span class="math inline">z</span>. From here on, you should by now be used to what comes next! As above, we use <span class="math inline">\breve{x}_i,\breve{y}_i</span> instead of <span class="math inline">x_i,y_i</span> in <a href="#eq-b1line" class="quarto-xref">Equation&nbsp;<span>5.9</span></a> to this time obtain:</p>
<p><span id="eq-line-centered"><span class="math display">
\begin{align}
b_1 &amp;= \frac{\frac{1}{N}\sum_{i=1}^N \breve{x}_i \breve{y}_i}{\frac{1}{N}\sum_{i=1}^N \breve{x}_i^2}\\
    &amp;= \frac{\frac{1}{N}\sum_{i=1}^N \frac{x_i - \bar{x}}{\sigma_x} \frac{y_i - \bar{y}}{\sigma_y}}{\frac{1}{N}\sum_{i=1}^N \left(\frac{x_i - \bar{x}}{\sigma_x}\right)^2} \\
    &amp;= \frac{Cov(x,y)}{\sigma_x \sigma_y} \\
    &amp;= Corr(x,y)  (\#eq:bline-standardized)
\end{align}
\tag{5.10}</span></span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>After we standardize both <span class="math inline">y</span> and <span class="math inline">x</span>, the slope coefficient <span class="math inline">b_1</span> in the regression without intercept is equal to the <strong>correlation coefficient</strong>.</p>
</div>
</div>
<p><br> And also for this case we have a practical application for you. Just type this and play around with the app for a little while!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"reg_standardized"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="pred-resids" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="pred-resids"><span class="header-section-number">5.3</span> Predictions and Residuals</h2>
<p>Now we want to ask how our residuals <span class="math inline">e_i</span> relate to the prediction <span class="math inline">\hat{y_i}</span>. Let us first think about the average of all predictions <span class="math inline">\hat{y_i}</span>, i.e.&nbsp;the number <span class="math inline">\frac{1}{N} \sum_{i=1}^N \hat{y_i}</span>. Let’s just take <a href="#eq-abline-pred" class="quarto-xref">Equation&nbsp;<span>5.2</span></a> and plug this into this average, so that we get</p>
<p><span class="math display">
\begin{align}
\frac{1}{N} \sum_{i=1}^N \hat{y_i} &amp;= \frac{1}{N} \sum_{i=1}^N b_0 + b_1 x_i \\
&amp;= b_0 + b_1  \frac{1}{N} \sum_{i=1}^N x_i \\
&amp;= b_0 + b_1  \bar{x} \\
\end{align}
</span></p>
<p>But that last line is just equal to the formula for the OLS intercept <a href="#eq-beta0hat" class="quarto-xref">Equation&nbsp;<span>5.6</span></a>, <span class="math inline">b_0 = \bar{y} - b_1 \bar{x}</span>! That means of course that</p>
<p><span class="math display">
\frac{1}{N} \sum_{i=1}^N \hat{y_i}  = b_0 + b_1  \bar{x} = \bar{y}
</span> in other words:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The average of our predictions <span class="math inline">\hat{y_i}</span> is identically equal to the mean of the outcome <span class="math inline">y</span>. This implies that the average of the residuals is equal to zero.</p>
</div>
</div>
<p><br> Related to this result, we can show that the prediction <span class="math inline">\hat{y}</span> and the residuals are <em>uncorrelated</em>, something that is often called <strong>orthogonality</strong> between <span class="math inline">\hat{y}_i</span> and <span class="math inline">e_i</span>. We would write this as</p>
<p><span class="math display">
\begin{align}
Cov(\hat{y},e) &amp;=\frac{1}{N} \sum_{i=1}^N (\hat{y}_i-\bar{y})(e_i-\bar{e}) =   \frac{1}{N} \sum_{i=1}^N (\hat{y}_i-\bar{y})e_i \\
&amp;=  \frac{1}{N} \sum_{i=1}^N \hat{y}_i e_i-\bar{y} \frac{1}{N} \sum_{i=1}^N e_i = 0
\end{align}
</span></p>
<p>It’s useful to bring back the sample data which generate figure <a href="#fig-line-arrows" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> at this point in order to verify these claims:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      y y_hat error
1  2.09  2.57 -0.48
2  2.79  3.41 -0.62
3  6.49  4.25  2.24
4  1.71  5.10 -3.39
5  9.89  5.94  3.95
6  7.62  6.78  0.83
7  4.86  7.63 -2.77
8  7.38  8.47 -1.09
9 10.63  9.31  1.32</code></pre>
</div>
</div>
<p>Let’s check that these claims are true in this sample of data. We want that</p>
<ol type="1">
<li>The average of <span class="math inline">\hat{y}_i</span> to be the same as the mean of <span class="math inline">y</span></li>
<li>The average of the errors should be zero.</li>
<li>Prediction and errors should be uncorrelated.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">mean</span>(ss<span class="sc">$</span>error), <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">mean</span>(ss<span class="sc">$</span>y_hat), <span class="fu">mean</span>(ss<span class="sc">$</span>y))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">cov</span>(ss<span class="sc">$</span>error,ss<span class="sc">$</span>y_hat), <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>So indeed we can confirm this result with our test dataset. Great!</p>
</section>
<section id="correlation-covariance-and-linearity" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="correlation-covariance-and-linearity"><span class="header-section-number">5.4</span> Correlation, Covariance and Linearity</h2>
<p>It is important to keep in mind that Correlation and Covariance relate to a <em>linear</em> relationship between <code>x</code> and <code>y</code>. Given how the regression line is estimated by OLS (see just above), you can see that the regression line inherits this property from the Covariance. A famous exercise by Francis Anscombe (1973) illustrates this by constructing 4 different datasets which all have identical <strong>linear</strong> statistics: mean, variance, correlation and regression line <em>are identical</em>. However, the usefulness of the statistics to describe the relationship in the data is not clear.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The important lesson from this example is the following:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Always <strong>visually inspect</strong> your data, and don’t rely exclusively on summary statistics like <em>mean, variance, correlation and regression line</em>. All of those assume a <strong>linear</strong> relationship between the variables in your data.</p>
</div>
</div>
<p><br> The mission of Anscombe has been continued recently. As a result of this we can have a look at the <code>datasauRus</code> package, which pursues Anscbombe’s idea through a multitude of funny data sets, all with the same linear statistics. Don’t just compute the covariance, or you might actually end up looking at a Dinosaur! What? Type this to find out:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">"datasaurus"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">aboutApp</span>(<span class="st">"datasaurus"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="non-linear-relationships-in-data" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="non-linear-relationships-in-data"><span class="header-section-number">5.4.1</span> Non-Linear Relationships in Data</h3>
<p>Suppose our data now looks like this:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/non-line-cars-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Putting our previous <em>best line</em> defined in equation <a href="#eq-abline" class="quarto-xref">Equation&nbsp;<span>5.3</span></a> as <span class="math inline">y = b_0 + b_1 x + e</span>, we get something like this:</p>
<div class="cell" data-fig-label="non-line-cars-ols">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>l1 <span class="ot">=</span> <span class="fu">lm</span>(mpg<span class="sc">~</span>hp,<span class="at">data=</span>mtcars)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars<span class="sc">$</span>hp,mtcars<span class="sc">$</span>mpg,<span class="at">xlab=</span><span class="st">"x"</span>,<span class="at">ylab=</span><span class="st">"y"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">reg=</span>l1,<span class="at">lw=</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Best line with non-linear data?</figcaption>
</figure>
</div>
</div>
</div>
<p>Somehow when looking at <span class="quarto-unresolved-ref">?fig-non-line-cars-ols</span> one is not totally convinced that the straight line is a good summary of this relationship. For values <span class="math inline">x\in[50,120]</span> the line seems to low, then again too high, and it completely misses the right boundary. It’s easy to address this shortcoming by including <em>higher order terms</em> of an explanatory variable. We would modify <a href="#eq-abline" class="quarto-xref">Equation&nbsp;<span>5.3</span></a> to read now</p>
<p><span id="eq-abline2"><span class="math display">
y_i = b_0 + b_1 x_i + b_2 x_i^2 + e_i
\tag{5.11}</span></span></p>
<p>This is a special case of <em>multiple regression</em>, which we will talk about in chapter <span class="citation" data-cites="multiple-reg">(<a href="references.html#ref-multiple-reg" role="doc-biblioref"><strong>multiple-reg?</strong></a>)</span>. You can see that there are <em>multiple</em> slope coefficients. For now, let’s just see how this performs:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/non-line-cars-ols2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Better line with non-linear data!</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="analysing-vary" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="analysing-vary"><span class="header-section-number">5.5</span> Analysing <span class="math inline">Var(y)</span></h2>
<p>Analysis of Variance (ANOVA) refers to a method to decompose variation in one variable as a function of several others. We can use this idea on our outcome <span class="math inline">y</span>. Suppose we wanted to know the variance of <span class="math inline">y</span>, keeping in mind that, by definition, <span class="math inline">y_i = \hat{y}_i + e_i</span>. We would write</p>
<p><span class="math display">\begin{align}
Var(y) &amp;= Var(\hat{y} + e)\\
&amp;= Var(\hat{y}) + Var(e) + 2 Cov(\hat{y},e)\\
&amp;= Var(\hat{y}) + Var(e) (\#eq:anova)
\end{align}</span></p>
<p>We have seen above in @ref(pred-resids) that the covariance between prediction <span class="math inline">\hat{y}</span> and error <span class="math inline">e</span> is zero, that’s why we have <span class="math inline">Cov(\hat{y},e)=0</span> in @ref(eq:anova). What this tells us in words is that we can decompose the variance in the observed outcome <span class="math inline">y</span> into a part that relates to variance as <em>explained by the model</em> and a part that comes from unexplained variation. Finally, we know the definition of <em>variance</em>, and can thus write down the respective formulae for each part:</p>
<ul>
<li><span class="math inline">Var(y) = \frac{1}{N}\sum_{i=1}^N (y_i - \bar{y})^2</span></li>
<li><span class="math inline">Var(\hat{y}) = \frac{1}{N}\sum_{i=1}^N (\hat{y_i} - \bar{y})^2</span>, because the mean of <span class="math inline">\hat{y}</span> is <span class="math inline">\bar{y}</span> as we know. Finally,</li>
<li><span class="math inline">Var(e) = \frac{1}{N}\sum_{i=1}^N e_i^2</span>, because the mean of <span class="math inline">e</span> is zero.</li>
</ul>
<p>We can thus formulate how the total variation in outcome <span class="math inline">y</span> is aportioned between model and unexplained variation:</p>
<div class="cell" type="tip">
<div class="tip">
<p>
The total variation in outcome <span class="math inline">(y)</span> (often called SST, or <em>total sum of squares</em>) is equal to the sum of explained squares (SSE) plus the sum of residuals (SSR). We have thus <strong>SST = SSE + SSR</strong>.
</p>
</div>
</div>
</section>
<section id="assessing-the-goodness-of-fit" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="assessing-the-goodness-of-fit"><span class="header-section-number">5.6</span> Assessing the <em>Goodness of Fit</em></h2>
<p>In our setup, there exists a convenient measure for how good a particular statistical model fits the data. It is called <span class="math inline">R^2</span> (<em>R squared</em>), also called the <em>coefficient of determination</em>. We make use of the just introduced decomposition of variance, and write the formula as</p>
<p><span class="math display">\begin{equation}
R^2 = \frac{\text{variance explained}}{\text{total variance}} = \frac{SSE}{SST} = 1 - \frac{SSR}{SST}\in[0,1]  (\#eq:Rsquared)
\end{equation}</span></p>
<p>It is easy to see that a <em>good fit</em> is one where the sum of <em>explained</em> squares (SSE) is large relativ to the total variation (SST). In such a case, we observe an <span class="math inline">R^2</span> close to one. In the opposite case, we will see an <span class="math inline">R^2</span> close to zero. Notice that a small <span class="math inline">R^2</span> does not imply that the model is useless, just that it explains a small fraction of the observed variation.</p>
</section>
<section id="an-example-a-log-wage-equation" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="an-example-a-log-wage-equation"><span class="header-section-number">5.7</span> An Example: A Log Wage Equation</h2>
<p>Let’s consider the following example concerning wage data collected in the 1976 Current Population Survey in the USA.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> We want to investigate the relationship between average hourly earnings, and years of education. Let’s start with a plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>, <span class="at">package =</span> <span class="st">"wooldridge"</span>)   <span class="co"># load data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># a function that returns a plot</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>plotfun <span class="ot">&lt;-</span> <span class="cf">function</span>(wage1,<span class="at">log=</span><span class="cn">FALSE</span>,<span class="at">rug =</span> <span class="cn">TRUE</span>){</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    y <span class="ot">=</span> wage1<span class="sc">$</span>wage</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (log){</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        y <span class="ot">=</span> <span class="fu">log</span>(wage1<span class="sc">$</span>wage)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(<span class="at">y =</span> y,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> wage1<span class="sc">$</span>educ, </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">pch =</span> <span class="dv">21</span>, <span class="at">bg =</span> <span class="st">"grey"</span>,     </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex=</span><span class="fl">1.25</span>, <span class="at">xaxt=</span><span class="st">"n"</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>,      <span class="co"># set default x-axis to none</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">ifelse</span>(log,<span class="st">"log(Wages) vs. Education, 1976"</span>,<span class="st">"Wages vs. Education, 1976"</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"years of education"</span>, </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="fu">ifelse</span>(log,<span class="st">"Log Hourly wages"</span>,<span class="st">"Hourly wages"</span>))</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">6</span>,<span class="dv">12</span>,<span class="dv">18</span>))         <span class="co"># add custom ticks to x axis</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (rug) <span class="fu">rug</span>(wage1<span class="sc">$</span>wage, <span class="at">side=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>)        <span class="co"># add `rug` to y axis</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))  <span class="co"># set up a plot with 2 panels</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 1: standard scatter plot</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="fu">plotfun</span>(wage1)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 2: add a panel with histogram+density</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(wage1<span class="sc">$</span>wage,<span class="at">prob =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"grey"</span>, <span class="at">border =</span> <span class="st">"red"</span>, </span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of wages and Density"</span>,<span class="at">xlab =</span> <span class="st">"hourly wage"</span>)</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(wage1<span class="sc">$</span>wage), <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lw =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/wooldridge-wages-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Wages vs Education from the wooldridge dataset wage1.</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking at the top panel of figure @ref(fig:wooldridge-wages), you notice two things: From the red ticks on the y axis, you see that wages are very concentrated at around 5 USD per hour, with fewer and fewer observations at higher rates; and second, that it seems that the hourly wage seems to increase with higher education levels. The bottom panel reinforces the first point, showing that the estimated pdf (probability density function) shown as a black line has a very long right tail: there are always fewer and fewer, but always larger and larger values of hourly wage in the data.</p>
<div class="cell" type="warning">
<div class="warning">
<p>
You have seen this shape of a distribution in the tutorial for chapter 2 already! Do you remember the name of this particular shape of a distribution? (why not type <code>ScPoEconometrics::runTutorial(‘chapter2’)</code>) to check?
</p>
</div>
</div>
<p><br></p>
<p>Let’s run a first regression on this data to generate some intution:</p>
<p><span class="math display">\begin{equation}
\text{wage}_i = b_0 + b_1 \text{educ}_i + e_i (\#eq:wage)
\end{equation}</span></p>
<p>We use the <code>lm</code> function for this purpose as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>hourly_wage <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> wage <span class="sc">~</span> educ, <span class="at">data =</span> wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>and we can add the resulting regression line to our above plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotfun</span>(wage1)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(hourly_wage, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">lw =</span> <span class="dv">2</span>) <span class="co"># add regression line</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/wooldridge-wages2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Wages vs Education from the wooldridge dataset wage1, with regression</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>hourly_wage</code> object contains the results of this estimation. We can get a summary of those results with the <code>summary</code> method:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hourly_wage)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ, data = wage1)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3396 -2.1501 -0.9674  1.1921 16.6085 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.90485    0.68497  -1.321    0.187    
educ         0.54136    0.05325  10.167   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.378 on 524 degrees of freedom
Multiple R-squared:  0.1648,    Adjusted R-squared:  0.1632 
F-statistic: 103.4 on 1 and 524 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The main interpretation of this table can be read off the column labelled <em>Estimate</em>, reporting estimated coefficients <span class="math inline">b_0,b_1</span>:</p>
<ol type="1">
<li>With zero year of education, the hourly wage is about -0.9 dollars per hour (row named <code>(Intercept)</code>)</li>
<li>Each additional year of education increase hourly wage by 54 cents. (row named <code>educ</code>)</li>
<li>For example, for 15 years of education, we predict roughly -0.9 + 0.541 * 15 = 7.215 dollars/h.</li>
</ol>
</section>
<section id="scaling-regressions" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="scaling-regressions"><span class="header-section-number">5.8</span> Scaling Regressions</h2>
<div class="cell" type="tip">
<div class="tip">
<p>
Regression estimates (<span class="math inline">(b_0, b_1)</span>) are in the scale <em>of the data</em>. The actual <em>value</em> of the estimates will vary, if we change the scale of the data. The overall fit of the model to the data would <em>not</em> change, however, so that the <span class="math inline">(R^2)</span> statistic would be constant.
</p>
</div>
</div>
<p><br></p>
<p>Suppose we wanted to use the above estimates to report the effect of years of education on <em>annual</em> wages instead of <em>hourly</em> ones. Let’s assume we have full-time workers, 7h per day, 5 days per week, 45 weeks per year. Calling this factor <span class="math inline">\delta = 7 \times 5 \times 45 = 1575</span>, we have that <span class="math inline">x</span> dollars per hour imply <span class="math inline">x \times \delta = x \times 1575</span> dollars per year.</p>
<p>What would be the effect of using <span class="math inline">\tilde{y} = wage \times 1575</span> instead of <span class="math inline">y = wage</span> as outcome variable on our regression coefficients <span class="math inline">b_0</span> and <span class="math inline">b_1</span>? Well, let’s try!</p>
<table style="text-align:center">
<caption>
<strong>Effect of Scaling on Coefficients</strong>
</caption>
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
wage
</td>
<td>
annual_wage
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
educ
</td>
<td>
0.541<sup>***</sup>
</td>
<td>
852.641<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.053)
</td>
<td>
(83.866)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-0.905
</td>
<td>
-1,425.141
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.685)
</td>
<td>
(1,078.824)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
526
</td>
<td>
526
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.165
</td>
<td>
0.165
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.163
</td>
<td>
0.163
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 524)
</td>
<td>
3.378
</td>
<td>
5,320.963
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 1; 524)
</td>
<td>
103.363<sup>***</sup>
</td>
<td>
103.363<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>Let’s call the coefficients in the column labelled (1) as <span class="math inline">b_0</span> and <span class="math inline">b_1</span>, and let’s call the ones in column (2) <span class="math inline">b_0^*</span> and <span class="math inline">b_1^*</span>. In column (1) we see that another year increaeses hourly wage by 0.54 dollars, as before. In column (2), the corresponding number is 852.64, i.e.&nbsp;another year of education will increase <em>annual</em> wages by 852.64 dollars, on average. Notice however, that <span class="math inline">b_0 \times \delta = -0.9 \times 1575 = -1425.14 = b_0^*</span> and that <span class="math inline">b_1 \times \delta = 0.54 \times 1575 = 852.64 = b_1^*</span>, that is we just had to multiply both coefficients by the scaling factor applied to original outcome <span class="math inline">y</span> to obtain our new coefficients <span class="math inline">b_0^*</span> and <span class="math inline">b_1^*</span>! Also, observe that the <span class="math inline">R^2</span>s of both regressions are identical! So, really, we did not have to run the regression in column (2) at all to make this change: multiplying all coefficients through by <span class="math inline">\delta</span> is enough in this case. We keep the identically same fit to the data.</p>
<p>Rescaling the regressors <span class="math inline">x</span> is slightly different, but it’s easy to work out <em>how</em> different, given the linear nature of the covariance operator, which is part of the OLS estimator. Suppose we rescale <span class="math inline">x</span> by the number <span class="math inline">c</span>. Then, using the OLS formula in @ref(eq:beta1hat), we see that we get new slope coefficient <span class="math inline">b_1^*</span> via</p>
<p><span class="math display">\begin{align}
b_1^* &amp;= \frac{Cov(cx,y)}{Var(cx)} \\
      &amp;= \frac{cCov(x,y)}{c^2 Var(x)} \\
      &amp;= \frac{1}{c} b_1.
\end{align}</span></p>
<p>As for the intercept, and by using @ref(eq:beta0hat) <span class="math display">\begin{align}
b_0^* &amp;= \bar{y} -             b_1^* \frac{1}{N}\sum_{i=1}^N c \cdot x_i \\
      &amp;= \bar{y} -             b_1^* \frac{c}{N}\sum_{i=1}^N x_i  \\
      &amp;= \bar{y} - \frac{1}{c} b_1 c * \bar{x}  \\
      &amp;= \bar{y} -  b_1 * \bar{x}  \\
      &amp;= b_0
\end{align}</span></p>
<p>That is, we change the slope by the <em>inverse</em> of the scaling factor applied to regressor <span class="math inline">x</span>, but the intercept is unaffected from this. You should play around for a while with our rescaling app to get a feeling for this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ScPoApps)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">launchApp</span>(<span class="st">'Rescale'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="a-particular-rescaling-the-log-transform" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="a-particular-rescaling-the-log-transform"><span class="header-section-number">5.9</span> A Particular Rescaling: The <span class="math inline">\log</span> Transform</h2>
<p>The natural logarithm is a particularly important transformation that we often encounter in economics. Why would we transform a variable with the <span class="math inline">\log</span> function to start with?</p>
<ol type="1">
<li>Several important economic variables (like wages, city size, firm size, etc) are approximately <em>log-normally</em> distributed. By transforming them with the <span class="math inline">\log</span>, we obtain an approximately <em>normally</em> distributed variable, which has desirable properties for our regression.</li>
<li>Applying the <span class="math inline">\log</span> reduces the impact of outliers.</li>
<li>The transformation allows for a convenient interpretation in terms of <em>percentage changes</em> of the outcome variable.</li>
</ol>
<p>Let’s investigate this issue in our running example by transforming the wage data above. Look back at the bottom panel of figure @ref(fig:wooldridge-wages): Of course you saw immediately that this looked a lot like a log-normal distribution, so point 1. above applies. We modify the left hand side of equation @ref(eq:wage):</p>
<p><span class="math display">\begin{equation}
\log(\text{wage}_i) = b_0 + b_1 \text{educ}_i + e_i (\#eq:log-wage)
\end{equation}</span></p>
<p>Let’s use the <code>update</code> function to modify our previous regression model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>log_hourly_wage <span class="ot">=</span> <span class="fu">update</span>(hourly_wage, <span class="fu">log</span>(wage) <span class="sc">~</span> ., <span class="at">data =</span> wage1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>update</code> function takes an existing <code>lm</code> object, like <code>hourly_wage</code> here, and updates the <code>formula</code>. Here the <code>.</code> on the right hand side means <em>leave unchanged</em> (so the RHS stays unchanged). How do our pictures change?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotfun</span>(wage1,<span class="at">rug =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(hourly_wage, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">lw =</span> <span class="dv">2</span>) <span class="co"># add regression line</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plotfun</span>(wage1,<span class="at">log =</span> <span class="cn">TRUE</span>, <span class="at">rug =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(log_hourly_wage, <span class="at">col =</span> <span class="st">'black'</span>, <span class="at">lw =</span> <span class="dv">2</span>) <span class="co"># add regression line</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/logplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>It <em>looks as if</em> the regression line has the same slope, but beware of the different scales of the y-axis! You can clearly see that all y-values have been compressed by the log transformation. The log case behaves differently from our <em>scaling by a constant number</em> case above because it is a <em>nonlinear</em> function. Let’s compare the output between both models:</p>
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_47qv8134690k7lj9ia16 = TinyTable.createTableFunctions("tinytable_47qv8134690k7lj9ia16");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '12', j: 2 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_y2kad98urbkmpon2d6rx',}, 
          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_lw3l92g0knmqdnrev9ky',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 } ], css_id: 'tinytable_css_40ga5vjzf9q9ppkjfmrm',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_3dqzrbl80w0rz6pvy7x9',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_6k59xesmix73tiajvdpt',}, 
          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_t13lhohi9iuqbjiqjelw',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_ulfqn2syrzeyrp8olx7s',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_x5eqecl4o45xlr5gl2a2',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_47qv8134690k7lj9ia16.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_y2kad98urbkmpon2d6rx, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_y2kad98urbkmpon2d6rx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_lw3l92g0knmqdnrev9ky, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_lw3l92g0knmqdnrev9ky {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_40ga5vjzf9q9ppkjfmrm, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_40ga5vjzf9q9ppkjfmrm { text-align: center }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_3dqzrbl80w0rz6pvy7x9, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_3dqzrbl80w0rz6pvy7x9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_6k59xesmix73tiajvdpt, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_6k59xesmix73tiajvdpt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_t13lhohi9iuqbjiqjelw, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_t13lhohi9iuqbjiqjelw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_ulfqn2syrzeyrp8olx7s, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_ulfqn2syrzeyrp8olx7s { text-align: left }
    #tinytable_47qv8134690k7lj9ia16 td.tinytable_css_x5eqecl4o45xlr5gl2a2, #tinytable_47qv8134690k7lj9ia16 th.tinytable_css_x5eqecl4o45xlr5gl2a2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_47qv8134690k7lj9ia16" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Log Transformed Equation</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
                <th scope="col" data-row="0" data-col="3">(2)</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">-0.905</td>
                  <td data-row="1" data-col="3">0.584</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.685)</td>
                  <td data-row="2" data-col="3">(0.097)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">educ</td>
                  <td data-row="3" data-col="2">0.541</td>
                  <td data-row="3" data-col="3">0.083</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.053)</td>
                  <td data-row="4" data-col="3">(0.008)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Num.Obs.</td>
                  <td data-row="5" data-col="2">526</td>
                  <td data-row="5" data-col="3">526</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1">R2</td>
                  <td data-row="6" data-col="2">0.165</td>
                  <td data-row="6" data-col="3">0.186</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">R2 Adj.</td>
                  <td data-row="7" data-col="2">0.163</td>
                  <td data-row="7" data-col="3">0.184</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1">AIC</td>
                  <td data-row="8" data-col="2">2777.4</td>
                  <td data-row="8" data-col="3">2432.4</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">BIC</td>
                  <td data-row="9" data-col="2">2790.2</td>
                  <td data-row="9" data-col="3">2445.2</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1">Log.Lik.</td>
                  <td data-row="10" data-col="2">-1385.712</td>
                  <td data-row="10" data-col="3">-359.378</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">F</td>
                  <td data-row="11" data-col="2">103.363</td>
                  <td data-row="11" data-col="3">119.582</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1">RMSE</td>
                  <td data-row="12" data-col="2">3.37</td>
                  <td data-row="12" data-col="3">0.48</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
<p>The interpretation of the transformed model in column (2) is now the following:</p>
<div class="cell" type="note">
<div class="note">
<p>
We call a regression of the form <span class="math inline">((y) = b_0 + b_1 x + u)</span> a <em>log-level</em> specification, because we regressed the log of a variable on the level (i.e not the log!) of another variable. Here, the impact of increasing <span class="math inline">(x)</span> by one unit is to increase <span class="math inline">(y)</span> by <span class="math inline">(100 b_1)</span> <strong>percent</strong>. In our example: an additional year of education will increase hourly wages by 8.3%. Notice that this is very different from saying <em>…increases log hourly wages by 8.3%</em>, which is wrong.
</p>
</div>
</div>
<p><br></p>
<p>Notice that the <span class="math inline">R^2</span> slightly improved, so have a better fit to the data. This is due the fact that the log compressed large outlier values. Whether we apply the <span class="math inline">log</span> to left or right-hand side variables makes a difference, as outlined in this important table:</p>
<center>

(#tab:loglog) Common Regression Specifications

</center>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Specification</th>
<th style="text-align: center;">Outcome Var</th>
<th style="text-align: center;">Regressor</th>
<th style="text-align: center;">Interpretation of <span class="math inline">b_1</span></th>
<th style="text-align: center;">Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Level-level</td>
<td style="text-align: center;">y</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"><span class="math inline">\Delta y = b_1 \Delta x</span></td>
<td style="text-align: center;">Standard</td>
</tr>
<tr class="even">
<td style="text-align: center;">Level-log</td>
<td style="text-align: center;">y</td>
<td style="text-align: center;"><span class="math inline">\log(x)</span></td>
<td style="text-align: center;"><span class="math inline">\Delta y = \frac{b_1}{100} \Delta x</span></td>
<td style="text-align: center;">less frequent</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Log-level</td>
<td style="text-align: center;"><span class="math inline">\log(y)</span></td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"><span class="math inline">\% \Delta y = (100 b_1) \Delta</span> x</td>
<td style="text-align: center;">Semi-elasticity</td>
</tr>
<tr class="even">
<td style="text-align: center;">Log-Log</td>
<td style="text-align: center;"><span class="math inline">\log(y)</span></td>
<td style="text-align: center;"><span class="math inline">\log(x)</span></td>
<td style="text-align: center;"><span class="math inline">\% \Delta y = \% \Delta</span> b_1 x</td>
<td style="text-align: center;">Elasticity</td>
</tr>
</tbody>
</table>
<p>You may remember from your introductory micro course what the definition of the <em>elasticity</em> of <span class="math inline">y</span> with respect to <span class="math inline">x</span> is: This number tells us by how many percent <span class="math inline">y</span> will change, if we change <span class="math inline">x</span> by one percent. Let’s look at another example from the <code>wooldridge</code> package of datasets, this time concerning CEO salaries and their relationship with company sales.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"ceosal1"</span>, <span class="at">package =</span> <span class="st">"wooldridge"</span>)  </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(salary <span class="sc">~</span> sales, <span class="at">data =</span> ceosal1, <span class="at">main =</span> <span class="st">"Sales vs Salaries"</span>,<span class="at">xaxt =</span> <span class="st">"n"</span>,<span class="at">frame =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">40000</span>, <span class="dv">80000</span>))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(ceosal1<span class="sc">$</span>salary,<span class="at">side =</span> <span class="dv">2</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(ceosal1<span class="sc">$</span>sales,<span class="at">side =</span> <span class="dv">1</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(salary) <span class="sc">~</span> <span class="fu">log</span>(sales), <span class="at">data =</span> ceosal1, <span class="at">main =</span> <span class="st">"Log(Sales) vs Log(Salaries)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-linear-regression_files/figure-html/ceo-sal-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The effect of log-transforming highly skewed data.</figcaption>
</figure>
</div>
</div>
</div>
<p>In the left panel of figure @ref(fig:ceo-sal) you clearly see that both <code>sales</code> and <code>salary</code> have very long right tails, as indicated by the rug plots on either axis. As a consequence, the points are clustered in the bottom left corner of the plot. We suspect a positive relationship, but it’s hard to see. Contrast this with the right panel, where both axis have been log transformed: the points are nicely spread out, clearly spelling out a positive correlation. Let’s see what this gives in a regression model!</p>
<p><span class="math display">\widehat{\log(salary)} = 4.82 + 0.26 \times \log(sales)</span></p>
<p>Refering back at table @ref(tab:loglog), here we have a log-log specification. Therefore we interpret this regression as follows:</p>
<div class="cell" type="tip">
<div class="tip">
<p>
In a log-log equation, the slope coefficient <span class="math inline">(b_1)</span> is the <em>elasticity of <span class="math inline">(y)</span> with respect to changes in <span class="math inline">(x)</span></em>. Here: A 1% increase in sales is associated to a 0.26% increase in CEO salaries. Note, again, that there is no <em>log</em> in this statement.
</p>
</div>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p> This slope is related to the angle between vectors <span class="math inline">\mathbf{a} = (\overline{x},\overline{y})</span>, and <span class="math inline">\mathbf{b} = (\overline{x},0)</span>. Hence, it’s related to the <a href="https://en.wikipedia.org/wiki/Scalar_projection">scalar projection</a> of <span class="math inline">\mathbf{a}</span> on <span class="math inline">\mathbf{b}</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This example is close to the vignette of the <a href="https://cloud.r-project.org/web/packages/wooldridge/index.html">wooldridge</a> package, whose author I hereby thank for the excellent work.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-statistics.html" class="pagination-link" aria-label="Review of Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review of Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-hypothesis-tests.html" class="pagination-link" aria-label="Hypothesis Tests">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>