<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Categorical Variables and Interactions – Econometrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-potential-issues.html" rel="next">
<link href="./06-multiple-regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-866c0150a82ceb70419aea9aa33b875d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-nonlinear-regression.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Variables and Interactions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Econometrics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to <code>R</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Probability for Economists</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review of Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-nonlinear-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Variables and Interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-potential-issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-star.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">STAR Experiment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Panel Data Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Instrumental Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-rdd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression Discontinuity Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Discrete Choice Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercises</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cruscotto-opere-pubbliche/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">In-Class Exercise: Public Works Cost Overruns Across Italian Provinces</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-binary-regressor-case" id="toc-the-binary-regressor-case" class="nav-link active" data-scroll-target="#the-binary-regressor-case"><span class="header-section-number">8.1</span> The Binary Regressor Case</a></li>
  <li><a href="#dummy-and-continuous-variables" id="toc-dummy-and-continuous-variables" class="nav-link" data-scroll-target="#dummy-and-continuous-variables"><span class="header-section-number">8.2</span> Dummy and Continuous Variables</a></li>
  <li><a href="#categorical-variables-in-r-factor" id="toc-categorical-variables-in-r-factor" class="nav-link" data-scroll-target="#categorical-variables-in-r-factor"><span class="header-section-number">8.3</span> Categorical Variables in <code>R</code>: <code>factor</code></a>
  <ul class="collapse">
  <li><a href="#more-levels" id="toc-more-levels" class="nav-link" data-scroll-target="#more-levels"><span class="header-section-number">8.3.1</span> More Levels</a></li>
  <li><a href="#sec-factors" id="toc-sec-factors" class="nav-link" data-scroll-target="#sec-factors"><span class="header-section-number">8.3.2</span> Log Wages and Dummies</a></li>
  </ul></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions"><span class="header-section-number">8.4</span> Interactions</a>
  <ul class="collapse">
  <li><a href="#interactions-with-dummies-differential-slopes" id="toc-interactions-with-dummies-differential-slopes" class="nav-link" data-scroll-target="#interactions-with-dummies-differential-slopes"><span class="header-section-number">8.4.1</span> Interactions with Dummies: Differential Slopes</a></li>
  </ul></li>
  <li><a href="#unobserved-individual-heterogeneity" id="toc-unobserved-individual-heterogeneity" class="nav-link" data-scroll-target="#unobserved-individual-heterogeneity"><span class="header-section-number">8.5</span> (Unobserved) Individual Heterogeneity</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-nonlinreg" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Categorical Variables and Interactions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Up until now, we have encountered only examples with <em>continuous</em> variables <span class="math inline">x</span> and <span class="math inline">y</span>, that is, <span class="math inline">x,y \in \mathbb{R}</span>, so that a typical observation could have been <span class="math inline">(y_i,x_i) = (1.5,5.62)</span>. There are many situations where it makes sense to think about the data in terms of <em>categories</em>, rather than continuous numbers. For example, whether an observation <span class="math inline">i</span> is <em>male</em> or <em>female</em>, whether a pixel on a screen is <em>black</em> or <em>white</em>, and whether a good was produced in <em>France</em>, <em>Germany</em>, <em>Italy</em>, <em>China</em> or <em>Spain</em> are all categorical classifications of data.</p>
<p>Probably the simplest type of categorical variable is the <em>binary</em>, <em>boolean</em>, or just <em>dummy</em> variable. As the name suggests, it can take on only two values, <code>0</code> and <code>1</code>, or <code>TRUE</code> and <code>FALSE</code>. Even though dummy variables only take two values, including them (possibly interacted with other regressors) is a simple and powerful way of letting the regression function take a more <em>flexible</em>, nonlinear shape across different subgroups of the data – which is exactly the topic of this chapter.</p>
<section id="the-binary-regressor-case" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="the-binary-regressor-case"><span class="header-section-number">8.1</span> The Binary Regressor Case</h2>
<p>Even though this is an extremely parsimonious way of encoding information, it is a very powerful tool that allows us to represent that a certain observation <span class="math inline">i</span> <strong>is a member</strong> of a certain category <span class="math inline">j</span>. For example, let’s imagine we have income data on males and females, and we would create a variable called <code>is.male</code> that is <code>TRUE</code> whenever <span class="math inline">i</span> is male, <code>FALSE</code> otherwise, and similarly for women. For example, to encode whether subject <span class="math inline">i</span> is male, one could do this:</p>
<p><span class="math display">
\text{is.male}_i =  \begin{cases}
                    1 &amp; \text{if }i\text{ is male} \\
                    0 &amp; \text{if }i\text{ is not male}. \\
                 \end{cases}
</span></p>
<p>and similarly for females, we’d have</p>
<p><span class="math display">
\text{is.female}_i =  \begin{cases}
                    1 &amp; \text{if }i\text{ is female} \\
                    0 &amp; \text{if }i\text{ is not female}. \\
                 \end{cases}
</span></p>
<p>By definition, we have just introduced a linear dependence into our dataset. It will always be true that <span class="math inline">\text{is.male}_i + \text{is.female}_i = 1</span>. This is because dummy variables are based on data being mutually exclusively categorized – here, you are either male or female.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This should immediately remind you of the discussion of <em>multicollinearity</em> in the chapter on multiple regression. A regression of income on both of our variables like this</p>
<p><span class="math display">
y_i = b_0 + b_1 \text{is.female}_i + b_2 \text{is.male}_i + e_i
</span></p>
<p>would be invalid because of perfect collinearity between <span class="math inline">\text{is.female}_i</span> and <span class="math inline">\text{is.male}_i</span>. The solution to this is pragmatic and simple:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In dummy variable regressions, we remove one category from the regression (for example here: <code>is.male</code>) and call it the <em>reference category</em>. The effect of being <em>male</em> is absorbed in the intercept. The coefficient on the remaining categories measures the <em>difference</em> in mean outcome with respect to the reference category.</p>
</div>
</div>
<p>Now let’s try this out. We start by creating the female indicator as above,</p>
<p><span class="math display">
\text{is.female}_i = \begin{cases}
          1 &amp; \text{if }i\text{ is female} \\
            0 &amp; \text{if }i\text{ is not female}. \\
   \end{cases}
</span></p>
<p>and let’s suppose that <span class="math inline">y_i</span> is a measure of <span class="math inline">i</span>’s annual labor income. Our model is</p>
<p><span id="eq-dummy-reg"><span class="math display">
y_i = b_0 + b_1 \text{is.female}_i + e_i
\tag{8.1}</span></span></p>
<p>and here is how we estimate this in <code>R</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dta<span class="sc">$</span>is.female <span class="ot">=</span> <span class="fu">factor</span>(x)  <span class="co"># convert x to factor</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dummy_reg <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>is.female,dta)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dummy_reg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ is.female, data = dta)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4253 -0.6551  0.1321  0.7217  2.8129 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.0568     0.2125   9.680 7.27e-13 ***
is.female1   -3.0169     0.3203  -9.418 1.74e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.124 on 48 degrees of freedom
Multiple R-squared:  0.6489,    Adjusted R-squared:  0.6416 
F-statistic:  88.7 on 1 and 48 DF,  p-value: 1.737e-12</code></pre>
</div>
</div>
<p>Notice that <code>R</code> displays the <em>level</em> of the factor to which coefficient <span class="math inline">b_1</span> belongs here, i.e.&nbsp;<code>is.female1</code> means this coefficient is on level <code>is.female = 1</code> – the reference level is <code>is.female = 0</code>, and it has no separate coefficient. Also interesting is that <span class="math inline">b_1</span> is equal to the difference in conditional means between male and female</p>
<p><span class="math display">b_1 = E[y|\text{is.female}=1] - E[y|\text{is.female}=0]=-3.0169.</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A dummy variable measures the difference or the <em>offset</em> in the mean of the response variable, <span class="math inline">E[y]</span>, <strong>conditional</strong> on <span class="math inline">x</span> belonging to some category – relative to a baseline category. In our artificial example, the coefficient <span class="math inline">b_1</span> informs us that women earn on average 3.017 units less than men.</p>
</div>
</div>
<p>It is instructive to reconsider this example graphically:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dummy-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dummy-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-nonlinear-regression_files/figure-html/fig-dummy-scatter-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dummy-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Regressing <span class="math inline">y \in \mathbb{R}</span> on <span class="math inline">\text{is.female}_i \in \{0,1\}</span>. The blue line is <span class="math inline">E[y]</span>, the red arrow is the size of <span class="math inline">b_1</span>. Which is the same as the slope of the regression line in this case and the difference in conditional means!
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-dummy-scatter" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> we see that this regression simplifies to the straight line connecting the mean, or the <em>expected value</em> of <span class="math inline">y</span> when <span class="math inline">\text{is.female}_i = 0</span>, i.e.&nbsp;<span class="math inline">E[y|\text{is.female}_i=0]</span>, to the mean when <span class="math inline">\text{is.female}_i=1</span>, i.e.&nbsp;<span class="math inline">E[y|\text{is.female}_i=1]</span>. It is useful to remember that the <em>unconditional mean</em> of <span class="math inline">y</span>, i.e.&nbsp;<span class="math inline">E[y]</span>, is going to be the result of regressing <span class="math inline">y</span> only on an intercept, illustrated by the blue line. This line will always lie in between both conditional means. As indicated by the red arrow, the estimate of the coefficient on the dummy, <span class="math inline">b_1</span>, is equal to the difference in conditional means for both groups.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you have access to the <code>ScPoApps</code> package, the interactive app <code>launchApp("reg_dummy")</code> lets you explore this relationship by dragging data points and watching the dummy coefficient update live.</p>
</div>
</div>
</section>
<section id="dummy-and-continuous-variables" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="dummy-and-continuous-variables"><span class="header-section-number">8.2</span> Dummy and Continuous Variables</h2>
<p>What happens if there are more predictors than just the dummy variable in a regression? For example, what if instead we had</p>
<p><span id="eq-dummy-reg2"><span class="math display">
y_i = b_0 + b_1 \text{is.female}_i + b_2 \text{exper}_i + e_i
\tag{8.2}</span></span></p>
<p>where <span class="math inline">\text{exper}_i</span> would measure years of experience in the labor market? As above, the dummy variable acts as an intercept shifter. We have</p>
<p><span class="math display">
y_i =  \begin{cases}
b_0 + b_1 + b_2 \times \text{exper}_i + e_i &amp; \text{if is.female=1} \\
b_0  + \hphantom{b_1} +b_2 \times \text{exper}_i + e_i &amp; \text{if is.female=0}
\end{cases}
</span></p>
<p>so that the intercept is <span class="math inline">b_0 + b_1</span> for women but <span class="math inline">b_0</span> for men. We will see this in the real-world example below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>ScPoApps</code> app <code>launchApp("reg_dummy_example")</code> lets you switch the dummy <em>on</em> and <em>off</em> interactively and observe how the fitted line jumps between the two parallel intercepts.</p>
</div>
</div>
</section>
<section id="categorical-variables-in-r-factor" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="categorical-variables-in-r-factor"><span class="header-section-number">8.3</span> Categorical Variables in <code>R</code>: <code>factor</code></h2>
<p><code>R</code> has extensive support for categorical variables built-in. The relevant data type representing a categorical variable is called <code>factor</code>. We encountered factors as a basic data type in the chapter on <code>R</code> basics already, but it is worth repeating this here. A factor <em>categorizes</em> a usually small number of numeric values by <em>labels</em>, as in this example which is similar to what we used to create regressor <code>is.female</code> for the above regression:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>is.female <span class="ot">=</span> <span class="fu">factor</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>,<span class="cn">TRUE</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>is.female</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE TRUE  TRUE  FALSE
Levels: FALSE TRUE</code></pre>
</div>
</div>
<p>You can see the result is a vector object of type <code>factor</code> with 4 entries, whereby <code>0</code> is represented as <code>FALSE</code> and <code>1</code> as <code>TRUE</code>. Another example could be if we wanted to record a variable <em>sex</em> instead, and we could do</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">=</span> <span class="fu">factor</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"male"</span>,<span class="st">"female"</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] male   female female male  
Levels: male female</code></pre>
</div>
</div>
<p>You can see that this is almost identical, just the <em>labels</em> are different.</p>
<section id="more-levels" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="more-levels"><span class="header-section-number">8.3.1</span> More Levels</h3>
<p>We can go beyond <em>binary</em> categorical variables such as <code>TRUE</code> vs <code>FALSE</code>. For example, suppose that <span class="math inline">x</span> measures educational attainment, i.e.&nbsp;it is now something like <span class="math inline">x_i \in \{\text{high school,some college,BA,MSc}\}</span>. In <code>R</code> parlance, <em>high school, some college, BA, MSc</em> are the <strong>levels of factor <span class="math inline">x</span></strong>. A straightforward extension of the above would dictate to create one dummy variable for each category (or level), like</p>
<p><span class="math display">
\begin{align*}
\text{has.HS}_i &amp;= \mathbf{1}[x_i==\text{high school}] \\
\text{has.someCol}_i &amp;= \mathbf{1}[x_i==\text{some college}] \\
\text{has.BA}_i &amp;= \mathbf{1}[x_i==\text{BA}] \\
\text{has.MSc}_i &amp;= \mathbf{1}[x_i==\text{MSc}]
\end{align*}
</span></p>
<p>but you can see that this is cumbersome. There is a better solution for us available:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">factor</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">4</span>),<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"HS"</span>,<span class="st">"someCol"</span>,<span class="st">"BA"</span>,<span class="st">"MSc"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] HS      HS      someCol MSc     BA      MSc    
Levels: HS someCol BA MSc</code></pre>
</div>
</div>
<p>Notice here that <code>R</code> will apply the labels in increasing order the way you supplied it (i.e.&nbsp;a numerical value <code>4</code> will correspond to “MSc”, no matter the ordering in <code>x</code>.)</p>
</section>
<section id="sec-factors" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="sec-factors"><span class="header-section-number">8.3.2</span> Log Wages and Dummies</h3>
<p>The above developed <code>factor</code> terminology fits neatly into <code>R</code>’s linear model fitting framework. Let us illustrate the simplest use by way of example.</p>
<p>Going back to our wage example, let’s say that a worker’s wage depends on their education as well as their sex:</p>
<p><span id="eq-wage-sex"><span class="math display">
\ln w_i = b_0 + b_1 educ_i + b_2 female_i + e_i
\tag{8.3}</span></span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"wage1"</span>, <span class="at">package =</span> <span class="st">"wooldridge"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>wage1<span class="sc">$</span>female <span class="ot">=</span> <span class="fu">as.factor</span>(wage1<span class="sc">$</span>female)  <span class="co"># convert 0-1 to factor</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>lm_w <span class="ot">=</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> educ, <span class="at">data =</span> wage1)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>lm_w_sex <span class="ot">=</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> female, <span class="at">data =</span> wage1)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>stargazer<span class="sc">::</span><span class="fu">stargazer</span>(lm_w,lm_w_sex,<span class="at">type =</span> <span class="cf">if</span> (knitr<span class="sc">:::</span><span class="fu">is_latex_output</span>()) <span class="st">"latex"</span> <span class="cf">else</span> <span class="st">"html"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table style="text-align:center">
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
lwage
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
educ
</td>
<td>
0.083<sup>***</sup>
</td>
<td>
0.077<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.008)
</td>
<td>
(0.007)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
female1
</td>
<td>
</td>
<td>
-0.361<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.039)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.584<sup>***</sup>
</td>
<td>
0.826<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.097)
</td>
<td>
(0.094)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
526
</td>
<td>
526
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.186
</td>
<td>
0.300
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.184
</td>
<td>
0.298
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.480 (df = 524)
</td>
<td>
0.445 (df = 523)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
119.582<sup>***</sup> (df = 1; 524)
</td>
<td>
112.189<sup>***</sup> (df = 2; 523)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>We know the results from column (1) very well by now. How does the relationship change if we include the <code>female</code> indicator? Remember from above that <code>female</code> is a <code>factor</code> with two levels, <em>0</em> and <em>1</em>, where <em>1</em> means <em>that’s a female</em>. We see in the above output that <code>R</code> included a regressor called <code>female1</code>. This is a combination of the variable name <code>female</code> and the level which was included in the regression. In other words, <code>R</code> chooses a <em>reference category</em> (by default the first of all levels by order of appearance), which is excluded – here this is <code>female==0</code>. The interpretation is that <span class="math inline">b_2</span> measures the effect of being female <em>relative</em> to being male. <code>R</code> automatically creates a dummy variable for each potential level, excluding the first category.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wage-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wage-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-nonlinear-regression_files/figure-html/fig-wage-plot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wage-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Log wage vs educ. Right panel with female dummy.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-wage-plot" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> illustrates this. The left panel is our previous model. The right panel adds the <code>female</code> dummy. You can see that both male and female have the same upward sloping regression line. But you can also see that there is a parallel downward shift from male to female line. The estimate of <span class="math inline">b_2 = -0.36</span> is the size of the downward shift.</p>
</section>
</section>
<section id="interactions" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="interactions"><span class="header-section-number">8.4</span> Interactions</h2>
<p>Sometimes it is useful to let the slope of a certain variable be dependent on the value of <em>another</em> regressor. For example consider a model for the sales prices of houses, where <code>area</code> is the livable surface of the property, and <code>age</code> is its age:</p>
<p><span id="eq-price-interact"><span class="math display">
\log(price) = b_0 + b_1 \text{area} + b_2 \text{age} + b_3 (\text{area} \times \text{age}) + e
\tag{8.4}</span></span></p>
<p>In that model, the partial effect of <code>area</code> on <code>log(price)</code>, keeping all other variables fixed, is</p>
<p><span class="math display">
\frac{\partial \log(price)}{\partial \text{area}} = b_1 + b_3 (\text{age})
</span></p>
<p>If we find that <span class="math inline">b_3 &gt; 0</span> in a regression, we conclude that the size of a house is valued more in older houses. We call <span class="math inline">b_3</span> the <strong>interaction effect</strong> between area and age. Let’s look at that regression model now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(hprice3, <span class="at">package =</span> <span class="st">"wooldridge"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(lprice <span class="sc">~</span> area<span class="sc">*</span>age, <span class="at">data =</span> hprice3))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lprice ~ area * age, data = hprice3)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27226 -0.16538 -0.00298  0.20673  0.83985 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.071e+01  6.633e-02 161.448  &lt; 2e-16 ***
area         3.647e-04  2.875e-05  12.686  &lt; 2e-16 ***
age         -7.377e-03  1.358e-03  -5.434  1.1e-07 ***
area:age     9.168e-07  4.898e-07   1.872   0.0622 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2925 on 317 degrees of freedom
Multiple R-squared:  0.5586,    Adjusted R-squared:  0.5545 
F-statistic: 133.7 on 3 and 317 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this instance, we see that indeed there is a small positive interaction between <code>area</code> and <code>age</code> on the sales price: even though <code>age</code> in isolation decreases the sales value, bigger houses command a small premium if they are older.</p>
<section id="interactions-with-dummies-differential-slopes" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="interactions-with-dummies-differential-slopes"><span class="header-section-number">8.4.1</span> Interactions with Dummies: Differential Slopes</h3>
<p>It is straightforward to extend the interactions logic to allow not only for different <em>intercepts</em>, but also different <em>slopes</em> for each subgroup in a dataset. Let’s go back to our dataset of wages from <a href="#sec-factors" class="quarto-xref"><span>Section 8.3.2</span></a> above. Now that we know how to create an interaction between two variables, we can easily modify <a href="#eq-wage-sex" class="quarto-xref">Equation&nbsp;<span>8.3</span></a> like this:</p>
<p><span id="eq-wage-sex2"><span class="math display">
\ln w = b_0 + b_1 \text{female} + b_2 \text{educ} + b_3 (\text{female} \times \text{educ}) + e
\tag{8.5}</span></span></p>
<p>The only peculiarity here is that <code>female</code> is a factor with levels <code>0</code> and <code>1</code>: i.e.&nbsp;the interaction term <span class="math inline">b_3</span> will be zero for all men. Similarly to above, we can test whether there are indeed different returns to education for men and women by looking at the estimated value <span class="math inline">b_3</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lm_w_interact <span class="ot">&lt;-</span> <span class="fu">lm</span>(lwage <span class="sc">~</span> educ <span class="sc">*</span> female , <span class="at">data =</span> wage1)  <span class="co"># R expands to full interactions model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_w_interact)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lwage ~ educ * female, data = wage1)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.02673 -0.27468 -0.03721  0.26221  1.34740 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   8.260e-01  1.181e-01   6.997 8.08e-12 ***
educ          7.723e-02  8.988e-03   8.593  &lt; 2e-16 ***
female1      -3.601e-01  1.854e-01  -1.942   0.0527 .  
educ:female1 -6.408e-05  1.450e-02  -0.004   0.9965    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4459 on 522 degrees of freedom
Multiple R-squared:  0.3002,    Adjusted R-squared:  0.2962 
F-statistic: 74.65 on 3 and 522 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We will in a later chapter learn how to formally test whether an estimate is different from zero in a statistical sense. For now, the estimate for <span class="math inline">b_3</span> on the interaction <code>educ:female1</code> is difficult for us to distinguish from zero; hence we conclude that there are <em>no</em> significantly different returns to education for men and women in this data. This is easy to verify visually in the following plot, where we are unable to detect a difference in slopes in the right panel.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wage-plot2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wage-plot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-nonlinear-regression_files/figure-html/fig-wage-plot2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wage-plot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: Log wage vs educ. Right panel allows slopes to be different – turns out they are not!
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-wage-plot2" class="quarto-xref">Figure&nbsp;<span>8.3</span></a> confirms the regression output: the two panels – one imposing parallel slopes, the other allowing them to differ – look virtually identical.</p>
</section>
</section>
<section id="unobserved-individual-heterogeneity" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="unobserved-individual-heterogeneity"><span class="header-section-number">8.5</span> (Unobserved) Individual Heterogeneity</h2>
<p>Finally, dummy variables are sometimes very important to account for spurious relationships in the data. Consider the following (artificial example):</p>
<ol type="1">
<li>Suppose we collected data on hourly wages together with the number of hours worked for a set of individuals.</li>
<li>We want to investigate the labour supply behaviour of those individuals, hence we run the regression <code>hours_worked ~ wage</code>.</li>
<li>We expect to get a positive coefficient on <code>wage</code>: the higher the wage, the more hours worked.</li>
<li>We know that individuals are members of either group <code>g=0</code> or <code>g=1</code>.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="fig-two-clouds-plain" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-clouds-plain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-nonlinear-regression_files/figure-html/fig-two-clouds-plain-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-clouds-plain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Hours worked vs wage, ignoring group membership.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-two-clouds-plain" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> shows a slightly negative relationship: higher wages are associated with fewer hours worked? Maybe. But wait, there is a group identifier in this data! Let’s use this and include <code>g</code> as a dummy in the regression – suppose <code>g</code> encodes male and female.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-two-clouds-group" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-clouds-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-nonlinear-regression_files/figure-html/fig-two-clouds-group-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-clouds-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: Left and right panel exhibit the same data. The right panel controls for group composition.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-two-clouds-group" class="quarto-xref">Figure&nbsp;<span>8.5</span></a> shows that, after conditioning on group membership <code>g</code>, the within-group relationship between wage and hours worked is actually <em>positive</em> for both groups – the overall negative slope we saw before was entirely driven by the fact that one group earns systematically higher wages <em>and</em> works systematically fewer hours, not by any genuine labour-supply response.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is an artificial example, yet it shows that you can be severely misled if you don’t account for group-specific effects in your data. The problem is particularly acute if we <em>don’t know</em> group membership – we can then resort to advanced methods, beyond the scope of this course, to <em>estimate</em> which group each individual belongs to. If we <em>do know</em> group membership, however, it is good practice to include a group dummy so as to control for group effects.</p>
</div>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>There are <a href="https://en.wikipedia.org/wiki/Transgender">transgender</a> individuals where this example will not apply.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-multiple-regression.html" class="pagination-link" aria-label="Multiple Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-potential-issues.html" class="pagination-link" aria-label="Causality">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causality</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>