project:
  type: book

book:
  title: "Econometrics"
  subtitle: "3rd Year Undergraduate, ESOMAS, Uni Turin"
  author: "Florian Oswald"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - 01-R.qmd
    - 02-probability.qmd
    - 03-statistics.qmd
    - 04-linear-regression.qmd
    - 05-hypothesis-tests.qmd
    - 06-multiple-regression.qmd
    - 07-nonlinear-regression.qmd
    - 09-potential-issues.qmd
    - 10-panel.qmd
    - 11-IV.qmd
    - 12-discrete.qmd
    - cruscotto-opere-pubbliche/exercise.qmd
    - references.qmd

bibliography: references.bib
html-math-method: katex

format:
  html:
    theme:
      - mystyle.scss
  pdf:
    documentclass: scrreprt



